name = "PowerTableDataParser"
uuid = "bed98974-b02a-5e2f-9ee0-a103f5c450dd"
authors = ["Daniel Thom, José Daniel Lara", "Hannah Chubin"]
version = "1.0.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
InfrastructureSystems = "2cd47ed4-ca9b-11e9-27f2-ab636a7671f1"

[compat]
DocStringExtensions = "~0.8, ~0.9"
InfrastructureSystems = "2.6.0"
julia = "^1.6"
