name = "PowerTableDataParser"
uuid = "bed98974-b02a-5e2f-9ee0-a103f5c450dd"
authors = ["Daniel Thom, José Daniel Lara", "Hannah Chubin"]
version = "1.0.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
InfrastructureSystems = "2cd47ed4-ca9b-11e9-27f2-ab636a7671f1"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"

[compat]
Dates = "1.11.0"
DocStringExtensions = "~0.8, ~0.9"
InfrastructureSystems = "2.6.0"
JSON3 = "1.14.3"
julia = "^1.6"
